名称: Docker镜像CI

启用:
推送:
分支: [ "main" ]
拉取请求:
分支: [ "main" ]

作业:

构建:

运行于: ubuntu-latest

步骤:
    - 使用: actions/checkout@v4
    - 名称: 构建Docker镜像
运行: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
